### ISSUE TITLE
python train.py error (2022-01-21)

### ISSUE THREAD

**Issue by chaaaning** [chaaaning/bp_road_crack_detection#9]
crack_data_loading.py를 바꾼 #8 에서 에러가 발생

**핵심적인 변경 사항**
1. mask data의 input을 annotaion 형태로 받고, PIL.Image로 바꿔 줌
2. 연속형의 annotation을 int로 바꿔 줌
3. annotation을 cv2.polyline으로 그려줌

```cmd
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    train_net(net=net,
  File "train.py", line 79, in train_net
    for batch in train_loader:
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\torch\utils\data\dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\Users\yunjc\_python_jupyter\bupyeonggu\bp_road_crack_detection\1_모델링\test_unet\utils\crack_data_loading.py", line 106, in __getitem__
    annot = self.load(ann_file[0])
  File "C:\Users\yunjc\_python_jupyter\bupyeonggu\bp_road_crack_detection\1_모델링\test_unet\utils\crack_data_loading.py", line 80, in load
    temp_int = np.apply_along_axis(np.int32, arr=temp, axis=0)
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "C:\Users\yunjc\anaconda3\envs\dl_env\lib\site-packages\numpy\lib\shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by chaaaning** [comment]
해당 코드는 경로 설정의 문제가 발생한 부분으로 보임. 코드는 images 경로에 있는 파일명을 받아 와서 마스킹 데이터 까지 불러오는데, 이 과정에서 .json에 파일이 없을 가능성이 있음. 데이터 관련 체크를 해 두고, `./Images` 경로의 파일과 `./Annoations` 경로의 파일 명을 비교해서 경로 관련 에러를 처리 해야 함.

**Comment by chaaaning** [comment]
관련 에러 문제 해결
참고 `ipynb` file : [data_error_check](https://github.com/chaaaning/bp_road_crack_detection/blob/main/1_%EB%AA%A8%EB%8D%B8%EB%A7%81/data_error_check.ipynb)
